[package]
name = "leaflet"
version = "0.1.2"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
description = "A wasm-bindgen wrapper for Leaflet.js"
homepage = "https://github.com/kartevonmorgen/leaflet-rs"
repository = "https://github.com/kartevonmorgen/leaflet-rs"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = ["Event", "HtmlElement"]

[badges]
maintenance = { status = "actively-developed" }
